#!/usr/bin/env python3
"""
Module for launching formater
"""
from cli import init_argparser
from db import init_styles_db


if __name__ == '__main__':
    db_config = init_styles_db()
    init_argparser(db_config)

