#!/usr/bin/env python3
"""
Module for launching formater
"""
import sys
from typing import List 

from formatter import Style, show_style 


if __name__ == '__main__':
    if len(sys.argv) <= 1:
        print("Не переданы аргументы")
        sys.exit(1)
    USER_INPUT = " ".join(sys.argv[1:])
    styles: List[Style] = Style.all_styles()
    style: Style = styles[0]
    show_style(style, USER_INPUT)
